# Generated by Django 3.2.3 on 2021-05-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import find_losts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_notification_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('longitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=14)),
                ('latitude', models.DecimalField(decimal_places=10, default=0.0, max_digits=14)),
                ('city', models.CharField(max_length=35)),
                ('is_matched', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='found', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'found_object',
            },
        ),
        migrations.CreateModel(
            name='LostObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=35)),
                ('is_matched', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='lost', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lost_object',
            },
        ),
        migrations.CreateModel(
            name='LostPersonImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=find_losts.models.lost_person_images)),
            ],
            options={
                'db_table': 'lost_person_image',
            },
        ),
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundobject')),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=700)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'found_item',
            },
        ),
        migrations.CreateModel(
            name='FoundPerson',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundobject')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=find_losts.models.found_person_images)),
            ],
            options={
                'db_table': 'found_person',
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.lostobject')),
                ('type', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=700)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'lost_item',
            },
        ),
        migrations.CreateModel(
            name='LostPerson',
            fields=[
                ('id', models.OneToOneField(blank=True, db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.lostobject')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=find_losts.models.lost_person_images)),
            ],
            options={
                'db_table': 'lost_person',
            },
        ),
        migrations.CreateModel(
            name='MatchedPerson',
            fields=[
                ('id_fp', models.OneToOneField(db_column='found_person_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='match', serialize=False, to='find_losts.foundobject')),
                ('date_of_receiving', models.DateTimeField(auto_now_add=True)),
                ('percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('id_lp', models.OneToOneField(db_column='lost_person_id', on_delete=django.db.models.deletion.CASCADE, related_name='match', to='find_losts.lostobject')),
                ('notify_id_fp', models.ForeignKey(db_column='notify_id_fp', on_delete=django.db.models.deletion.CASCADE, related_name='reach_match_to_who_found', to='notification.notification')),
                ('notify_id_lp', models.ForeignKey(db_column='notify_id_lp', on_delete=django.db.models.deletion.CASCADE, related_name='reach_match_to_who_lost', to='notification.notification')),
            ],
            options={
                'db_table': 'matched_Person',
            },
        ),
        migrations.CreateModel(
            name='FoundPersonImage',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='find_losts.foundperson')),
                ('image', models.ImageField(unique=True, upload_to='')),
            ],
            options={
                'db_table': 'found_person_image',
                'unique_together': {('id', 'image')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_matched', models.BooleanField(default=False)),
                ('notify_id', models.ForeignKey(db_column='notify_id', on_delete=django.db.models.deletion.CASCADE, related_name='reach_candidates_to_who_found', to='notification.notification')),
                ('id_fi', models.ForeignKey(db_column='found_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='find_losts.founditem')),
                ('id_li', models.ForeignKey(db_column='lost_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='find_losts.lostitem')),
            ],
            options={
                'db_table': 'candidate',
                'unique_together': {('id_li', 'id_fi')},
            },
        ),
    ]
