# Generated by Django 3.2.3 on 2021-06-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_losts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchedperson',
            name='percent',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
